const DEBUG_VISUALIZE_DISTANCE_TRANSFORM = true;
const DEBUG_VISUALIZE_MINCUT_AND_INTERIOR = true;
const DEBUG_VISUALIZE_ALTERNATIVE_MINCUTS = true;
const DEBUG_VISUALIZE_SEEDS = true;
const DEBUG_VISUALIZE_PROGRESS = true;
const BASE_PLAIN_COST = 1;
const BASE_SWAMP_COST = 2;
const BLOCKING_COST = 50;
const MAX_DISTANCE = 255;
const SEED_DISTANCE = 4;
const SEED_RANGE = 3;
const EXIT_BLOCK_RANGE = 3;
const MINCUT_EXIT_BLOCK_RANGE = 1;
const MINCUT_SOURCE_EXIT_RANGE = 2;
const MINCUT_SOURCE_EXPAND_RANGE = 2;
const MINCUT_MAX_TRIES = 255;
const MIN_BUILDABLE_TILES = 155;
const LARGE_AREA_RADIUS = 3;
const LARGE_CORE_RADIUS = 2;
const SMALL_AREA_RADIUS = 2;
const SMALL_CORE_RADIUS = 1;
const EIGHT_NEIGHBOR_VECTORS = [
  { x: 0, y: -1 },
  { x: 1, y: -1 },
  { x: 1, y: 0 },
  { x: 1, y: 1 },
  { x: 0, y: 1 },
  { x: -1, y: 1 },
  { x: -1, y: 0 },
  { x: -1, y: -1 },
];
const MINCUT_POS_BITS = 1 << 12;
const MINCUT_POS_MASK = MINCUT_POS_BITS - 1;
const MINCUT_OUT_NODE = 1 << 12;
const MINCUT_MAX_NODE = 1 << 13;
const MINCUT_NODE_MASK = MINCUT_MAX_NODE - 1;
const MINCUT_INSIDE_EDGE = 1 << 16;
const MINCUT_DIR_SHIFT = 13;
const MINCUT_INF_CAPACITY = 10000;
const MINCUT_MAX_FLOW_ITERATIONS = 50;
const ROOM_PLAN_MINCUT_DONE = 1;
const ROOM_PLAN_STEP2_DONE = 2;
const STEP2_EXTENSION_FF_RESERVED = 16;
const DEBUG_VISUALIZE_STEP2_CORES = true;
const TERRAIN_BLOCKING_COST = 255;
const STEP2_TEMP_BLOCK_CONTROLLER_RANGE = 3;
const STEP2_TEMP_BLOCK_RESOURCE_RANGE = 1;
const STEP2_TOWER_COUNT = 6;
const STEP2_LAB_COUNT = 10;
const STEP2_EXTENSION_START_INDEX = 17;
const STEP2_EXTENSION_COUNT = 60;
const ACCESS_REPAIR_ROAD_COST = 1;
const ACCESS_REPAIR_EXTENSION_COST = 10;
const ACCESS_REPAIR_TERRAIN_COST = 8;
const ACCESS_REPAIR_MAX_TRIES = 1000;

module.exports = {
  DEBUG_VISUALIZE_DISTANCE_TRANSFORM,
  DEBUG_VISUALIZE_MINCUT_AND_INTERIOR,
  DEBUG_VISUALIZE_ALTERNATIVE_MINCUTS,
  DEBUG_VISUALIZE_SEEDS,
  DEBUG_VISUALIZE_PROGRESS,
  DEBUG_VISUALIZE_STEP2_CORES,
  BASE_PLAIN_COST,
  BASE_SWAMP_COST,
  BLOCKING_COST,
  MAX_DISTANCE,
  SEED_DISTANCE,
  SEED_RANGE,
  EXIT_BLOCK_RANGE,
  MINCUT_EXIT_BLOCK_RANGE,
  MINCUT_SOURCE_EXIT_RANGE,
  MINCUT_SOURCE_EXPAND_RANGE,
  MINCUT_MAX_TRIES,
  MIN_BUILDABLE_TILES,
  LARGE_AREA_RADIUS,
  LARGE_CORE_RADIUS,
  SMALL_AREA_RADIUS,
  SMALL_CORE_RADIUS,
  EIGHT_NEIGHBOR_VECTORS,
  MINCUT_POS_BITS,
  MINCUT_POS_MASK,
  MINCUT_OUT_NODE,
  MINCUT_MAX_NODE,
  MINCUT_NODE_MASK,
  MINCUT_INSIDE_EDGE,
  MINCUT_DIR_SHIFT,
  MINCUT_INF_CAPACITY,
  MINCUT_MAX_FLOW_ITERATIONS,
  ROOM_PLAN_MINCUT_DONE,
  ROOM_PLAN_STEP2_DONE,
  STEP2_EXTENSION_FF_RESERVED,
  TERRAIN_BLOCKING_COST,
  STEP2_TEMP_BLOCK_CONTROLLER_RANGE,
  STEP2_TEMP_BLOCK_RESOURCE_RANGE,
  STEP2_TOWER_COUNT,
  STEP2_LAB_COUNT,
  STEP2_EXTENSION_START_INDEX,
  STEP2_EXTENSION_COUNT,
  ACCESS_REPAIR_ROAD_COST,
  ACCESS_REPAIR_EXTENSION_COST,
  ACCESS_REPAIR_TERRAIN_COST,
  ACCESS_REPAIR_MAX_TRIES,
};
